<!--
  PhonologyDesigner — Interactive IPA chart for selecting phonemes.

  Mirrors the TUI designer: browse consonants/vowels by articulation, toggle
  phonemes on/off, and see real words generated by the Rust engine with their
  IPA transcriptions. Bundled inventories can be loaded as a starting point.
-->
<script>
  import { presets } from './engine.js';

  let { engine } = $props();

  // IPA consonant chart data
  const IPA_CONSONANTS = [
    { label: 'Plosive', sounds: ['p','b','t','d','ʈ','ɖ','c','ɟ','k','g','q','ɢ','ʔ'] },
    { label: 'Nasal', sounds: ['m','ɱ','n','ɳ','ɲ','ŋ','ɴ'] },
    { label: 'Fricative', sounds: ['ɸ','β','f','v','θ','ð','s','z','ʃ','ʒ','x','ɣ','h','ɦ'] },
    { label: 'Affricate', sounds: ['ts','dz','tʃ','dʒ'] },
    { label: 'Approximant', sounds: ['w','ʋ','l','j','ɹ','ɻ'] },
    { label: 'Trill/Tap', sounds: ['ɾ','r','ʀ'] },
  ];
  const IPA_VOWELS = [
    { label: 'Close', sounds: ['i','y','ɨ','ʉ','ɯ','u'] },
    { label: 'Near-close', sounds: ['ɪ','ʏ','','','ʊ'] },
    { label: 'Close-mid', sounds: ['e','ø','ɘ','ɵ','ɤ','o'] },
    { label: 'Mid', sounds: ['','','ə','','',''] },
    { label: 'Open-mid', sounds: ['ɛ','œ','ɜ','ɞ','ʌ','ɔ'] },
    { label: 'Open', sounds: ['æ','','ɐ','','ɑ','ɒ'] },
  ];

  // Selected phonemes and configuration (Svelte 5 runes)
  let vowels = $state(['a','e','i','o','u']);
  let consonants = $state(['p','t','k','m','n','s','l','r','h']);
  let syllableStructure = $state('CV');
  let tones = $state(false);
  let toneCount = $state(4);
  let vowelHarmony = $state(false);
  let syllables = $state(3);
  let seed = $state('');

  let samples = $state([]);
  let error = $state('');

  // Bundled inventories, read straight from the engine's embedded registries.
  const { phonologies } = presets();
  const presetNames = Object.keys(phonologies).sort();
  let selectedPreset = $state('');

  /** Load a bundled inventory into the chart. */
  function loadPreset(name) {
    const preset = phonologies[name];
    if (!preset) return;
    vowels = [...preset.vowels];
    consonants = [...preset.consonants];
    syllableStructure = preset.syllable_structure;
    tones = preset.tones != null;
    toneCount = preset.tones ?? 4;
    vowelHarmony = preset.vowel_harmony ?? false;
    regenerate();
  }

  function toggle(list, sound) {
    return list.includes(sound) ? list.filter((s) => s !== sound) : [...list, sound];
  }

  function toggleConsonant(sound) {
    if (!sound) return;
    consonants = toggle(consonants, sound);
    regenerate();
  }

  function toggleVowel(sound) {
    if (!sound) return;
    vowels = toggle(vowels, sound);
    regenerate();
  }

  /**
   * Generate sample words from the current inventory.
   *
   * The engine rejects inventories that cannot fill their own template — no
   * vowels with a `V` slot, for instance — so its message is shown as-is
   * rather than guessed at here.
   */
  function regenerate() {
    error = '';
    try {
      samples = engine.generateWords({
        vowels,
        consonants,
        syllableStructure,
        tones: tones ? toneCount : null,
        vowelHarmony,
        syllables: Math.max(1, syllables),
        count: 12,
        seed: seed === '' ? null : seed,
      });
    } catch (e) {
      samples = [];
      error = e.message;
    }
  }

  // Generate an initial sample set on mount.
  regenerate();
</script>

<div class="designer">
  <h2>Phonology Designer</h2>

  <div class="status">
    <span>C: {consonants.length}</span>
    <span>V: {vowels.length}</span>
    <span>Structure:
      <input type="text" bind:value={syllableStructure} oninput={regenerate} style="width:90px" />
    </span>
    <span>Syllables:
      <input type="number" min="1" max="8" bind:value={syllables} oninput={regenerate} style="width:50px" />
    </span>
    <label>
      <input type="checkbox" bind:checked={tones} onchange={regenerate} /> Tones
      <input type="number" min="1" max="5" bind:value={toneCount} oninput={regenerate} disabled={!tones} style="width:45px" />
    </label>
    <label><input type="checkbox" bind:checked={vowelHarmony} onchange={regenerate} /> Harmony</label>
    <span>Seed:
      <input type="number" bind:value={seed} oninput={regenerate} placeholder="random" style="width:90px" />
    </span>
    <button onclick={regenerate}>Regenerate</button>
  </div>

  <div class="status">
    <span>Load inventory:</span>
    <select bind:value={selectedPreset} onchange={() => loadPreset(selectedPreset)}>
      <option value="">— bundled phonologies —</option>
      {#each presetNames as name}<option value={name}>{name}</option>{/each}
    </select>
    <button onclick={() => { vowels = ['a','i','u']; consonants = ['p','t','k','m','n','s']; regenerate(); }}>Minimal</button>
    <button onclick={() => { vowels = ['a','e','i','o','u']; consonants = ['p','b','t','d','k','g','m','n','f','v','s','z','h','l','r','j','w']; regenerate(); }}>Full</button>
  </div>

  {#if error}
    <div class="error">{error}</div>
  {:else}
    <div class="samples">
      {#each samples as sample}
        <div class="sample">
          <span class="word">{sample.word}</span>
          <span class="ipa">{sample.ipa}</span>
        </div>
      {/each}
      {#if samples.length === 0}
        <div class="empty">No words could be generated from this inventory.</div>
      {/if}
    </div>
  {/if}

  <div class="grids">
    <div class="grid">
      <h3>Consonants</h3>
      {#each IPA_CONSONANTS as row}
        <div class="ipa-row">
          <span class="label">{row.label}</span>
          {#each row.sounds as sound}
            {#if sound}
              <button
                class="phoneme"
                class:selected={consonants.includes(sound)}
                onclick={() => toggleConsonant(sound)}
              >{sound}</button>
            {:else}
              <span class="empty-slot"></span>
            {/if}
          {/each}
        </div>
      {/each}
    </div>

    <div class="grid">
      <h3>Vowels</h3>
      {#each IPA_VOWELS as row}
        <div class="ipa-row">
          <span class="label">{row.label}</span>
          {#each row.sounds as sound}
            {#if sound}
              <button
                class="phoneme"
                class:selected={vowels.includes(sound)}
                onclick={() => toggleVowel(sound)}
              >{sound}</button>
            {:else}
              <span class="empty-slot"></span>
            {/if}
          {/each}
        </div>
      {/each}
    </div>
  </div>
</div>

<style>
  .designer { padding: 1rem; }
  .status { display: flex; gap: 1rem; align-items: center; flex-wrap: wrap; margin-bottom: 0.5rem; padding: 0.5rem; background: #161b22; border-radius: 6px; }
  .status span, .status label { font-size: 0.9rem; display: flex; align-items: center; gap: 0.3rem; }
  .status button { padding: 0.25rem 0.75rem; background: #21262d; color: #c9d1d9; border: 1px solid #30363d; border-radius: 4px; cursor: pointer; }
  .status input, .status select { background: #0d1117; color: #c9d1d9; border: 1px solid #30363d; border-radius: 4px; padding: 0.2rem; }
  .samples { display: flex; flex-wrap: wrap; gap: 0.5rem; margin: 1rem 0; }
  .sample { padding: 0.4rem 0.7rem; background: #0d419d; border-radius: 4px; font-family: ui-monospace, monospace; display: flex; flex-direction: column; gap: 0.15rem; }
  .sample .word { font-weight: 600; }
  .sample .ipa { color: #d2a8ff; font-size: 0.8rem; }
  .error { padding: 0.5rem; background: #490202; color: #f85149; border-radius: 4px; margin: 1rem 0; }
  .empty { padding: 1rem; color: #484f58; }
  .grids { display: flex; gap: 2rem; flex-wrap: wrap; }
  .grid { flex: 1; min-width: 300px; }
  .ipa-row { display: flex; align-items: center; gap: 0.15rem; margin-bottom: 0.25rem; }
  .label { font-size: 0.75rem; color: #8b949e; min-width: 90px; }
  button.phoneme {
    width: 36px; height: 32px; font-size: 0.85rem;
    background: #21262d; color: #484f58;
    border: 1px solid #30363d; border-radius: 4px; cursor: pointer;
    transition: all 0.1s;
  }
  button.phoneme:hover { background: #30363d; }
  button.phoneme.selected { background: #238636; color: #fff; border-color: #2ea043; }
  .empty-slot { width: 36px; }
</style>
